export const ROOM_AMENITIES = [
  'Air Conditioning',
  'Wi-Fi',
  'TV',
  'Mini Bar',
  'Safe',
  'Desk',
  'Balcony',
  'Ocean View',
  'Mountain View',
  'City View',
  'Kitchen',
  'Living Room',
  'Dining Area',
  'Coffee Maker',
  'Hair Dryer',
  'Iron',
  'Phone',
  'Room Service',
  'Laundry Service',
  'Gym Access',
  'Pool Access',
  'Spa Access',
  'Restaurant Access',
  'Parking',
  'Elevator Access'
]
